services:
  comfyui:
    container_name: comfyui-iguruspain-cu128
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    image: comfyui-triton-sageatt:cu128

    ports:
      - "8188:8188"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${FOLDER}/models:/home/ubuntu/ComfyUI/models:rw
      - ${FOLDER}/custom_nodes:/home/ubuntu/ComfyUI/custom_nodes:rw
      - ${FOLDER}/user:/home/ubuntu/ComfyUI/user:rw
      - ${FOLDER}/output:/home/ubuntu/ComfyUI/output:rw
      - ${FOLDER}/input:/home/ubuntu/ComfyUI/input:rw
    environment:
      - CLI_ARGS=
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
